name: "CLA Assistant"

on:
  workflow_call:

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.3.2
        env:
          # CLA Action uses this in-built GitHub token to make the API calls for interacting with GitHub.
          # It is built into Github Actions and does not need to be manually specified in your secrets store.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The below token should have repo scope and must be manually added by you in the repository's secret
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_CONFIG_PERSONAL_ACCESS_TOKEN }}
        with:
          path-to-signatures: "signatures/v2.0.0/cla.json"
          path-to-document: "https://github.com/tmtecnologia/.github/blob/main/cla.md"
          allowlist: dependabot
          # branch should not be protected
          branch: "main"
          remote-organization-name: "TMTecnologia"
          remote-repository-name: "clabot-config"
          lock-pullrequest-aftermerge: false
          custom-notsigned-prcomment: |
            'Thanks 💖 for your submission! We ask that $you sign our [Contributor
            License Agreement](https://github.com/devopness/.github/blob/main/CLA.md)
            before we can accept your contribution. You can sign the CLA by
            adding a comment below using this text:'
